# Generated by Django 4.1.2 on 2023-01-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruit',
            old_name='company',
            new_name='company_id',
        ),
    ]
