# Generated by Django 4.1.2 on 2022-10-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
